### ISSUE TITLE
Improve dark mode handling in oranda-css

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#390]
From Discord:

fwiw i think the way we're doing dark toggling is a bit cumbersome/brittle? Instead of having 

```css
.dark .blah {
  color: var(--dark-fg-color);
} 
.blah {
  color: var(--light-fg-color);
}
```

we can just do

```css
:root {
  --fg-color: var(--light-fg-color);
}
:root.dark {
  --fg-color: var(--dark-fg-color);
}

.blah {
  color: var(--fg-color);
}
```
no more "oops you forgot to add a dark variant for that component"
