### ISSUE TITLE
Allow publishing only on release

### ISSUE THREAD

**Issue by konstin** [axodotdev/oranda#646]
I often make changes to the documentation that are only available with the next release. It would be nice if there was an option to only update the live website when a non-preview release is published.

**Comment by manyinsects** [comment]
I _believe_ GitHub actions support this as a trigger:

```yaml
on:
  release:
    types: [released] # as opposed to [prereleased]
```
