### ISSUE TITLE
Doc-comments incorrectly suggest `web.yml` can be manually run.

### ISSUE THREAD

**Issue by dream-dasher** [axodotdev/oranda#708]
I believe the following is required to allow manual activation of a github workflow.
```yml
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```

It's is not present in **web.yml** yet the doc comments in there specifically mention being able to manually run.
(`You can, of course, also manually trigger a workflow run when you want the docs to update.`)
```yml
on:
  ...
  # If you only want docs to update with releases, disable this, or change it to
  # a "release" branch. You can, of course, also manually trigger a workflow run
  # when you want the docs to update.
  push:
    branches:
      - main
```
